### ISSUE TITLE
obj2ifc for multiple obj files

### ISSUE THREAD

**Issue by HollowHeartNet** [Martin15135215/git_ifc_test#1]
Dear Martin,

I found your script obj2ifc_pymeshlab.py and I am very grateful for your efforts. Your current implementation only considers the conversion of a single OBJ file into IFC. I wanted to ask you how your script needs to be modified to convert multiple OBJ files into a single IFC file. Unfortunately, I was not able to do that with a for loop.

I hope you understand my question. 
Thanks in advance

With best regards
HollowHeartNet

**Comment by Martin15135215** [comment]
Hoi @HollowHeartNet 

It was not at all my own effort. Here is the orignial script https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc.py and the one modified to use meshlab https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/scripts/obj2ifc-meshlab.py

To your question

you need something like that:

```python
obj2ifc = Obj2ifc()
obj2ifc.create_ifc_file()
for path in path_list:
	obj2ifc.execute(path)
obj2ifc.write_ifc_file(new_path_name)
```

to use it like that, the scripts needs a little bit of modification. I hope that can lead you enough, if not, i see it then

Best Regards
Martin

**Comment by HollowHeartNet** [comment]
Dear Martin,

Thank you for the swift response.
I have tried this:

```
import pymeshlab
import ifcopenshell
import ifcopenshell.api
import ifcopenshell.api.owner.settings
from pathlib import Path


class Obj2Ifc:
    def __init__(self, fileList):
        self.fileList = fileList

    def execute(self): #convert mesh to ifc
        self.create_ifc_file()

        for i in range(len(self.fileList)):
            self.basename = Path(self.fileList[i]).stem
            print("filename:", self.basename)

            ### start ###
            mesh_set = pymeshlab.MeshSet()
            mesh_set.load_new_mesh(self.fileList[i])

            self.format = None
            if self.fileList[i].lower().endswith(".obj"):
                self.format = "obj"

            for mesh in mesh_set:
                faces = mesh.face_matrix()
                vertices = mesh.vertex_matrix()

                ifc_faces = []
                for face in faces:
                    ifc_faces.append(
                        self.file.createIfcFace(
                            [
                                self.file.createIfcFaceOuterBound(
                                    self.file.createIfcPolyLoop(
                                        [self.file.createIfcCartesianPoint(vertices[index].tolist()) for index in face]
                                    ),
                                    True,
                                )
                            ]
                        )
                    )
                representation = self.file.createIfcProductDefinitionShape(
                    None,
                    None,
                    [
                        self.file.createIfcShapeRepresentation(
                            self.context,
                            "Body",
                            "Brep",
                            [self.file.createIfcFacetedBrep(self.file.createIfcClosedShell(ifc_faces))],
                        )
                    ],
                )
                product = self.file.create_entity(
                    "IfcWall", #Insert IfcClass here
                    **{
                        "GlobalId": ifcopenshell.guid.new(),
                        "Name": self.basename,
                        "ObjectPlacement": self.placement,
                        "Representation": representation,
                    }
                )
                ifcopenshell.api.run("spatial.assign_container", self.file, product=product, relating_structure=self.storey)
                ### end ###
        self.file.write("SORTIE_MODEL.ifc")

    def get_coordinates(self, coordinates):
        if self.format == "obj":
            # OBJ swaps Y and Z axis
            return [coordinates[0], -coordinates[2], coordinates[1]]

    def create_ifc_file(self):
        self.file = ifcopenshell.api.run("project.create_file", version="IFC4")
        person = ifcopenshell.api.run("owner.add_person", self.file)
        person[0] = person.GivenName = None
        person.FamilyName = "user"
        org = ifcopenshell.api.run("owner.add_organisation", self.file)
        org[0] = None
        org.Name = "template"
        user = ifcopenshell.api.run("owner.add_person_and_organisation", self.file, person=person, organisation=org)
        application = ifcopenshell.api.run("owner.add_application", self.file)
        ifcopenshell.api.owner.settings.get_user = lambda ifc: user
        ifcopenshell.api.owner.settings.get_application = lambda ifc: application

        project = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcProject", name="SORTIE-IFC")
        lengthunit = ifcopenshell.api.run("unit.add_si_unit", self.file, unit_type="LENGTHUNIT", name="METRE")
        ifcopenshell.api.run("unit.assign_unit", self.file, units=[lengthunit])
        model = ifcopenshell.api.run("context.add_context", self.file, context_type="Model")
        self.context = ifcopenshell.api.run(
            "context.add_context",
            self.file,
            context_type="Model",
            context_identifier="Body",
            target_view="MODEL_VIEW",
            parent=model,
        )
        site = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcSite", name="My Site")
        building = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcBuilding", name="My Building")
        self.storey = ifcopenshell.api.run(
            "root.create_entity", self.file, ifc_class="IfcBuildingStorey", name="My Storey"
        )
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=site, relating_object=project)
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=building, relating_object=site)
        ifcopenshell.api.run("aggregate.assign_object", self.file, product=self.storey, relating_object=building)

        self.origin = self.file.createIfcAxis2Placement3D(
            self.file.createIfcCartesianPoint((0.0, 0.0, 0.0)),
            self.file.createIfcDirection((0.0, 0.0, 1.0)),
            self.file.createIfcDirection((1.0, 0.0, 0.0)),
        )
        self.placement = self.file.createIfcLocalPlacement(None, self.origin)
        self.history = ifcopenshell.api.run("owner.create_owner_history", self.file)


if __name__ == "__main__":

    file1 = "test_obj2ifc.obj"
    file2 = "test2_obj2ifc.obj"
    filelist = [file1, file2]

    obj2ifc = Obj2Ifc(filelist)
    obj2ifc.execute()
```

The above code takes into account the for loop as you mentioned. However, I get the following error message:

```
Traceback (most recent call last):
  File ".\obj2ifc.py", line 147, in <module>
    obj2ifc.execute()
  File ".\obj2ifc.py", line 79, in execute
    product = self.file.create_entity(
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\file.py", line 284, in create_entity
    e[idx] = arg
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\entity_instance.py", line 224, in __setitem__
    self.method_list[idx](
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4867, in setArgumentAsEntityInstance
    return _ifcopenshell_wrapper.entity_ins
```

Do you know the reason for this error? 
Can you please help?

Thanks in advance!

With best regards
HollowHeartNet

**Comment by Martin15135215** [comment]
@HollowHeartNet Could you please test the new script https://github.com/Martin15135215/git_ifc_test/blob/main/multiplteOBJ2IFC.py

It takes as a argument the directory

`python multiplteOBJ2IFC.py dir_path`

**Comment by Martin15135215** [comment]
> Dear Martin,
> 
> Thank you for the swift response. I have tried this:
> 
> ```
> import pymeshlab
> import ifcopenshell
> import ifcopenshell.api
> import ifcopenshell.api.owner.settings
> from pathlib import Path
> 
> 
> class Obj2Ifc:
>     def __init__(self, fileList):
>         self.fileList = fileList
> 
>     def execute(self): #convert mesh to ifc
>         self.create_ifc_file()
> 
>         for i in range(len(self.fileList)):
>             self.basename = Path(self.fileList[i]).stem
>             print("filename:", self.basename)
> 
>             ### start ###
>             mesh_set = pymeshlab.MeshSet()
>             mesh_set.load_new_mesh(self.fileList[i])
> 
>             self.format = None
>             if self.fileList[i].lower().endswith(".obj"):
>                 self.format = "obj"
> 
>             for mesh in mesh_set:
>                 faces = mesh.face_matrix()
>                 vertices = mesh.vertex_matrix()
> 
>                 ifc_faces = []
>                 for face in faces:
>                     ifc_faces.append(
>                         self.file.createIfcFace(
>                             [
>                                 self.file.createIfcFaceOuterBound(
>                                     self.file.createIfcPolyLoop(
>                                         [self.file.createIfcCartesianPoint(vertices[index].tolist()) for index in face]
>                                     ),
>                                     True,
>                                 )
>                             ]
>                         )
>                     )
>                 representation = self.file.createIfcProductDefinitionShape(
>                     None,
>                     None,
>                     [
>                         self.file.createIfcShapeRepresentation(
>                             self.context,
>                             "Body",
>                             "Brep",
>                             [self.file.createIfcFacetedBrep(self.file.createIfcClosedShell(ifc_faces))],
>                         )
>                     ],
>                 )
>                 product = self.file.create_entity(
>                     "IfcWall", #Insert IfcClass here
>                     **{
>                         "GlobalId": ifcopenshell.guid.new(),
>                         "Name": self.basename,
>                         "ObjectPlacement": self.placement,
>                         "Representation": representation,
>                     }
>                 )
>                 ifcopenshell.api.run("spatial.assign_container", self.file, product=product, relating_structure=self.storey)
>                 ### end ###
>         self.file.write("SORTIE_MODEL.ifc")
> 
>     def get_coordinates(self, coordinates):
>         if self.format == "obj":
>             # OBJ swaps Y and Z axis
>             return [coordinates[0], -coordinates[2], coordinates[1]]
> 
>     def create_ifc_file(self):
>         self.file = ifcopenshell.api.run("project.create_file", version="IFC4")
>         person = ifcopenshell.api.run("owner.add_person", self.file)
>         person[0] = person.GivenName = None
>         person.FamilyName = "user"
>         org = ifcopenshell.api.run("owner.add_organisation", self.file)
>         org[0] = None
>         org.Name = "template"
>         user = ifcopenshell.api.run("owner.add_person_and_organisation", self.file, person=person, organisation=org)
>         application = ifcopenshell.api.run("owner.add_application", self.file)
>         ifcopenshell.api.owner.settings.get_user = lambda ifc: user
>         ifcopenshell.api.owner.settings.get_application = lambda ifc: application
> 
>         project = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcProject", name="SORTIE-IFC")
>         lengthunit = ifcopenshell.api.run("unit.add_si_unit", self.file, unit_type="LENGTHUNIT", name="METRE")
>         ifcopenshell.api.run("unit.assign_unit", self.file, units=[lengthunit])
>         model = ifcopenshell.api.run("context.add_context", self.file, context_type="Model")
>         self.context = ifcopenshell.api.run(
>             "context.add_context",
>             self.file,
>             context_type="Model",
>             context_identifier="Body",
>             target_view="MODEL_VIEW",
>             parent=model,
>         )
>         site = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcSite", name="My Site")
>         building = ifcopenshell.api.run("root.create_entity", self.file, ifc_class="IfcBuilding", name="My Building")
>         self.storey = ifcopenshell.api.run(
>             "root.create_entity", self.file, ifc_class="IfcBuildingStorey", name="My Storey"
>         )
>         ifcopenshell.api.run("aggregate.assign_object", self.file, product=site, relating_object=project)
>         ifcopenshell.api.run("aggregate.assign_object", self.file, product=building, relating_object=site)
>         ifcopenshell.api.run("aggregate.assign_object", self.file, product=self.storey, relating_object=building)
> 
>         self.origin = self.file.createIfcAxis2Placement3D(
>             self.file.createIfcCartesianPoint((0.0, 0.0, 0.0)),
>             self.file.createIfcDirection((0.0, 0.0, 1.0)),
>             self.file.createIfcDirection((1.0, 0.0, 0.0)),
>         )
>         self.placement = self.file.createIfcLocalPlacement(None, self.origin)
>         self.history = ifcopenshell.api.run("owner.create_owner_history", self.file)
> 
> 
> if __name__ == "__main__":
> 
>     file1 = "test_obj2ifc.obj"
>     file2 = "test2_obj2ifc.obj"
>     filelist = [file1, file2]
> 
>     obj2ifc = Obj2Ifc(filelist)
>     obj2ifc.execute()
> ```
> 
> The above code takes into account the for loop as you mentioned. However, I get the following error message:
> 
> ```
> Traceback (most recent call last):
>   File ".\obj2ifc.py", line 147, in <module>
>     obj2ifc.execute()
>   File ".\obj2ifc.py", line 79, in execute
>     product = self.file.create_entity(
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\file.py", line 284, in create_entity
>     e[idx] = arg
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\entity_instance.py", line 224, in __setitem__
>     self.method_list[idx](
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4867, in setArgumentAsEntityInstance
>     return _ifcopenshell_wrapper.entity_ins
> ```
> 
> Do you know the reason for this error? Can you please help?
> 
> Thanks in advance!
> 
> With best regards HollowHeartNet

Mabye this line ` "ObjectPlacement": self.placement,` makes the problem, try to change to ` "ObjectPlacement": None,`

**Comment by HollowHeartNet** [comment]
Dear Martin,

Setting ObjectPlacement to None solved the problem.
Thank you!

The issue can be closed.

**Comment by Martin15135215** [comment]
futer note

there is a bug in run("spatial.assign_container" see https://github.com/IfcOpenShell/IfcOpenShell/issues/2789


use this

```python
product = self.file.create_entity(
                    "IfcWall", #Insert IfcClass here
                    **{
                        "GlobalId": ifcopenshell.guid.new(),
                        "Name": self.basename,
                        "ObjectPlacement": None,
                        "Representation": representation,
                    }
                )

ifcopenshell.api.run("spatial.assign_container", self.file, product=product, relating_structure=self.storey)
product.ObjectPlacement = self.placement
```
